### ISSUE TITLE
Calendar Help!

### ISSUE THREAD

**Issue by jodiedoubleday** [Aerolab/rooms#3]
Thank you very much for this repo, I think it will help me and my team out immensely.
I'm having issues seeing the details of the events in a particular calendar. It seems as though when you try and share the calendar with the service ID it only gives you the options to see busy/free rather than full permissions.

I wondered if you had this problem and if so how you overcome it?
I had to set up a role for our service account which is set up as 'owner' and we still can't see information about an event on the service.

Any help much appreciated.

**Comment by RobertoGonzalez** [comment]
Hi! That sounds like an issue with calendar. If that’s the case, you need to go to the settings for the calendar for each room and then set the app id (it looks like an email) as an owner. There you should be able to give it full read and write permissions.
If that doesn’t work, I’d look into making the calendars public, which should fix the visibility issue. 

Cheers!
