### ISSUE TITLE
Background colour favicon.ico isn't referenced?

### ISSUE THREAD

**Issue by Liam-Dow** [Aerolab/rooms#4]
I can't seem to get the favicon.ico to appear as the background colour.  The favicon changes on my browser, but the background colour is black whether it's booked or available. Can't see the favicon.ico being referenced in the css files either. Any ideas how to get it to work? Great project by the way, thanks for supporting open source.

**Comment by RobertoGonzalez** [comment]
Hi @KingPartimidas! The favicon is a leftover from the first version. The new design has a dark background and just shows a high contrast button when the room is available.

If you want to apply a specific style to the entire app when it's available, you should be able to use the `isAvailable` variable in App.js renderer, and add some CSS for that particular scenario.
