### ISSUE TITLE
Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by oguilleux** [Aerolab/rooms#6]
I'm getting the error above in [App.js at line 90](https://github.com/Aerolab/rooms/blob/master/src/App.js#L90)

It seems to come from `const roomData = await roomReq.json();` above.

I don't have node.js on my server only php and apache.

Thanks for you help,

**Comment by RobertoGonzalez** [comment]
You need a Node.JS server to run the application, as it has quite a bit of serverside logic. You should try Heroku.com or Now.sh if you want to ship quickly.
